// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import CardNav from "../components/Components/CardNav/CardNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  
  // Define the navigation data
  const navItems = [
    {
      label: "About",
      bgColor: "#000000",
      textColor: "#ffffff",
      links: [
        { label: "About", href: "/about", ariaLabel: "Learn about our company" },
      ]
    },
    {
      label: "Projects",
      bgColor: "#000000",
      textColor: "#ffffff",
      links: [
        { label: "Featured", href: "/featured", ariaLabel: "View featured projects" }
      ]
    },
    {
      label: "Services",
      bgColor: "#000000",
      textColor: "#ffffff",
      links: [
        { label: "Development", href: "/development", ariaLabel: "Our development services" }
      ]
    }
  ];

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.className} antialiased min-h-screen`}>
        <CardNav 
          logo="/logo2.png"
          logoAlt="Uncu Worklabs"
          items={navItems}
          baseColor="#ffffff"
          buttonBgColor="#22c55e"
          buttonTextColor="#ffffff"
        />
        <main>{children}</main>
      </body>
    </html>
  );
}